### ISSUE TITLE
Requirements file creation

### ISSUE THREAD

**Issue by markdicks** [VenusChappie/Next.js-Portfolio-Project#3]
This file will hold the information of required packages that our script will read from. Will allow easy modifications to requirements in the future as well, allowing people who don't know much about scripting to add requirements if modification of code/issues are found in the future that require such modifications.

**Comment by VenusChappie** [comment]
Hey Mark!

These should be all the requirements necessary for the script. If not just reach out and update them. 

[requirements.txt](https://github.com/user-attachments/files/16180317/requirements.txt)

I can work on the readme so long. Make it more descriptive and stuff.

**Comment by markdicks** [comment]
Ok sick, looks good.
